### PR TITLE
Syntactic constructs

### PR DESCRIPTION
**Pull request by salehsedghpour**
locating syntactic constructs are added. The following constructs are supported:

- Loop
- If
- Assertion
- Switch
- Synchronized
- Flow Break
- Try

### CODE REVIEW

**Comment by Deee92** [comment]
@khaes-kth, can you take this one?

**Comment by khesoem** [comment]
@Deee92 Yes, I will take this.

@salehsedghpour I will wait for you to adapt it to work with the output of my parser.

**Comment by salehsedghpour** [comment]
I checked, it works fine, because I didn't changed the output format. but there is one conflict that we should resolve.
In `src/main/java/se/wasp/one/runner/OneCommand.java` the conflict is on the following:
`    private final static Logger LOGGER = Logger.getLogger(OneCommand.class.getName());
`
or 
`private final static Logger LOGGER = Logger.getLogger(Main.class.getName());`

@khaes-kth I don't know the reason it is changed, if we fix this, the rest will work fine in `one`. but I couldn't make the parser work!

**Comment by salehsedghpour** [comment]
@khaes-kth 
I checked the parser itself, it does not work.
 `spoon.compiler.ModelBuildingException: The type NeuronString is already defined
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.reportProblem(JDTBasedSpoonCompiler.java:600)
	at spoon.support.compiler.jdt.TreeBuilderRequestor.acceptResult(TreeBuilderRequestor.java:29)
	at spoon.support.compiler.jdt.TreeBuilderCompiler.buildUnits(TreeBuilderCompiler.java:110)
	at spoon.support.compiler.jdt.JDTBatchCompiler.getUnits(JDTBatchCompiler.java:283)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildUnits(JDTBasedSpoonCompiler.java:417)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildUnitsAndModel(JDTBasedSpoonCompiler.java:369)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildSources(JDTBasedSpoonCompiler.java:335)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.build(JDTBasedSpoonCompiler.java:116)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.build(JDTBasedSpoonCompiler.java:99)
	at spoon.Launcher.buildModel(Launcher.java:781)
	at se.wasp.parser.runner.ParserLauncher.<init>(ParserLauncher.java:28)
	at se.wasp.parser.runner.ParserCommand.call(ParserCommand.java:26)
	at se.wasp.parser.runner.ParserCommand.call(ParserCommand.java:13)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2311)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at se.wasp.Main.main(Main.java:8)`

**Comment by khesoem** [comment]
> I checked, it works fine, because I didn't changed the output format. but there is one conflict that we should resolve. In `src/main/java/se/wasp/one/runner/OneCommand.java` the conflict is on the following: ` private final static Logger LOGGER = Logger.getLogger(OneCommand.class.getName());` or `private final static Logger LOGGER = Logger.getLogger(Main.class.getName());`
> 
> @khaes-kth I don't know the reason it is changed, if we fix this, the rest will work fine in `one`. but I couldn't make the parser work!

I think you should `git rebase` your code with my branch.

**Comment by khesoem** [comment]
> @khaes-kth I checked the parser itself, it does not work. `spoon.compiler.ModelBuildingException: The type NeuronString is already defined at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.reportProblem(JDTBasedSpoonCompiler.java:600) at spoon.support.compiler.jdt.TreeBuilderRequestor.acceptResult(TreeBuilderRequestor.java:29) at spoon.support.compiler.jdt.TreeBuilderCompiler.buildUnits(TreeBuilderCompiler.java:110) at spoon.support.compiler.jdt.JDTBatchCompiler.getUnits(JDTBatchCompiler.java:283) at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildUnits(JDTBasedSpoonCompiler.java:417) at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildUnitsAndModel(JDTBasedSpoonCompiler.java:369) at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildSources(JDTBasedSpoonCompiler.java:335) at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.build(JDTBasedSpoonCompiler.java:116) at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.build(JDTBasedSpoonCompiler.java:99) at spoon.Launcher.buildModel(Launcher.java:781) at se.wasp.parser.runner.ParserLauncher.<init>(ParserLauncher.java:28) at se.wasp.parser.runner.ParserCommand.call(ParserCommand.java:26) at se.wasp.parser.runner.ParserCommand.call(ParserCommand.java:13) at picocli.CommandLine.executeUserObject(CommandLine.java:1953) at picocli.CommandLine.access$1300(CommandLine.java:145) at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352) at picocli.CommandLine$RunLast.handle(CommandLine.java:2346) at picocli.CommandLine$RunLast.handle(CommandLine.java:2311) at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179) at picocli.CommandLine.execute(CommandLine.java:2078) at se.wasp.Main.main(Main.java:8)`

How did you check it? What was your input?

**Comment by salehsedghpour** [comment]
> > I checked, it works fine, because I didn't changed the output format. but there is one conflict that we should resolve. In `src/main/java/se/wasp/one/runner/OneCommand.java` the conflict is on the following: ` private final static Logger LOGGER = Logger.getLogger(OneCommand.class.getName());` or `private final static Logger LOGGER = Logger.getLogger(Main.class.getName());`
> > @khaes-kth I don't know the reason it is changed, if we fix this, the rest will work fine in `one`. but I couldn't make the parser work!
> 
> I think you should `git rebase` your code with my branch.

Done and force repushed!  :D

**Comment by salehsedghpour** [comment]
> > @khaes-kth I checked the parser itself, it does not work. `spoon.compiler.ModelBuildingException: The type NeuronString is already defined at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.reportProblem(JDTBasedSpoonCompiler.java:600) at spoon.support.compiler.jdt.TreeBuilderRequestor.acceptResult(TreeBuilderRequestor.java:29) at spoon.support.compiler.jdt.TreeBuilderCompiler.buildUnits(TreeBuilderCompiler.java:110) at spoon.support.compiler.jdt.JDTBatchCompiler.getUnits(JDTBatchCompiler.java:283) at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildUnits(JDTBasedSpoonCompiler.java:417) at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildUnitsAndModel(JDTBasedSpoonCompiler.java:369) at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildSources(JDTBasedSpoonCompiler.java:335) at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.build(JDTBasedSpoonCompiler.java:116) at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.build(JDTBasedSpoonCompiler.java:99) at spoon.Launcher.buildModel(Launcher.java:781) at se.wasp.parser.runner.ParserLauncher.<init>(ParserLauncher.java:28) at se.wasp.parser.runner.ParserCommand.call(ParserCommand.java:26) at se.wasp.parser.runner.ParserCommand.call(ParserCommand.java:13) at picocli.CommandLine.executeUserObject(CommandLine.java:1953) at picocli.CommandLine.access$1300(CommandLine.java:145) at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352) at picocli.CommandLine$RunLast.handle(CommandLine.java:2346) at picocli.CommandLine$RunLast.handle(CommandLine.java:2311) at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179) at picocli.CommandLine.execute(CommandLine.java:2078) at se.wasp.Main.main(Main.java:8)`
> 
> How did you check it? What was your input?

My bad, I checked on the root of One! but when I've checked on src folder (for instance) it worked!

**Comment by khesoem** [comment]
Since we decided to develop units in separate repos, I'm closing this PR.

**Pull request closed without merging**
